/**
 * @typedef {"active" | "suspended" | "blocked"} CustomerStatus
 * @typedef {"new" | "returning" | "vip" | "at-risk" | "lapsed"} CustomerSegment
 *
 * @typedef {{
 *   id:        string,
 *   name:      string,
 *   email:     string,
 *   phone:     string,
 *   country:   string,
 *   orders:    number,
 *   spent:     number,
 *   tier:      string,
 *   segment:   CustomerSegment,
 *   status:    CustomerStatus,
 *   joined:    string,
 *   avatar:    string,
 * }} Customer
 */

/** @type {Customer[]} */
export const customers = [
  {
    id: "C001",
    name: "Sarah Johnson",
    email: "sarah@email.com",
    phone: "+1 555 0101",
    country: "🇺🇸 USA",
    orders: 24,
    spent: 4280.0,
    tier: "Gold",
    segment: "vip",
    status: "active",
    joined: "Jan 12, 2025",
    avatar: "SJ",
  },
  {
    id: "C002",
    name: "Ahmed Hassan",
    email: "ahmed@email.com",
    phone: "+20 10 0001",
    country: "🇪🇬 Egypt",
    orders: 3,
    spent: 210.0,
    tier: "Bronze",
    segment: "new",
    status: "active",
    joined: "Mar 1, 2026",
    avatar: "AH",
  },
  {
    id: "C003",
    name: "Juliet Romeo",
    email: "juliet@email.com",
    phone: "+44 7911 01",
    country: "🇬🇧 UK",
    orders: 18,
    spent: 3120.0,
    tier: "Silver",
    segment: "returning",
    status: "active",
    joined: "Jun 5, 2024",
    avatar: "JR",
  },
  {
    id: "C004",
    name: "Peter Pan",
    email: "peter@email.com",
    phone: "+61 4 0001",
    country: "🇦🇺 AUS",
    orders: 1,
    spent: 45.0,
    tier: "Bronze",
    segment: "at-risk",
    status: "active",
    joined: "Feb 10, 2026",
    avatar: "PP",
  },
  {
    id: "C005",
    name: "Maria Garcia",
    email: "maria@email.com",
    phone: "+34 6 00001",
    country: "🇪🇸 Spain",
    orders: 41,
    spent: 9100.0,
    tier: "Platinum",
    segment: "vip",
    status: "active",
    joined: "Mar 3, 2023",
    avatar: "MG",
  },
  {
    id: "C006",
    name: "Viju Mike",
    email: "viju@email.com",
    phone: "+234 80 001",
    country: "🇳🇬 Nigeria",
    orders: 0,
    spent: 0,
    tier: "Bronze",
    segment: "lapsed",
    status: "suspended",
    joined: "Nov 20, 2024",
    avatar: "VM",
  },
  {
    id: "C007",
    name: "Linda Osei",
    email: "linda@email.com",
    phone: "+233 24 001",
    country: "🇬🇭 Ghana",
    orders: 9,
    spent: 1450.0,
    tier: "Silver",
    segment: "returning",
    status: "active",
    joined: "Sep 14, 2024",
    avatar: "LO",
  },
  {
    id: "C008",
    name: "Kwame Asante",
    email: "kwame@email.com",
    phone: "+233 50 001",
    country: "🇬🇭 Ghana",
    orders: 5,
    spent: 680.0,
    tier: "Bronze",
    segment: "at-risk",
    status: "active",
    joined: "Dec 3, 2024",
    avatar: "KA",
  },
  {
    id: "C009",
    name: "Chloe Laurent",
    email: "chloe@email.com",
    phone: "+33 6 00001",
    country: "🇫🇷 France",
    orders: 30,
    spent: 6200.0,
    tier: "Gold",
    segment: "vip",
    status: "active",
    joined: "Apr 22, 2023",
    avatar: "CL",
  },
  {
    id: "C010",
    name: "James Okafor",
    email: "james@email.com",
    phone: "+234 81 001",
    country: "🇳🇬 Nigeria",
    orders: 2,
    spent: 120.0,
    tier: "Bronze",
    segment: "new",
    status: "active",
    joined: "Mar 20, 2026",
    avatar: "JO",
  },
];

export const columns = [
  { label: "" },
  { label: "Customer" },
  { label: "Country" },
  { label: "Orders" },
  { label: "Spent" },
  { label: "Tier" },
  { label: "Segment" },
  { label: "Status" },
  { label: "Actions" },
];

/** @type {string[]} */
export const avatarColors = [
  "#6366f1",
  "#ec4899",
  "#14b8a6",
  "#f59e0b",
  "#8b5cf6",
  "#10b981",
  "#f97316",
  "#06b6d4",
  "#84cc16",
  "#ef4444",
];

export const segments = ["all", "new", "returning", "vip", "at-risk", "lapsed"];
